config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  get 'reports/index'
  get 'reports/long'
  get 'reports/client'

  resources :attendances do
    get 'change', on: :collection
    post 'bulk', on: :collection
  end

  resources :works

  resources :payments

  resources :clients

  resources :labours do
    get 'salary', on: :collection
    get 'attendance', on: :collection
    post 'bs', on: :collection
    post 'as', on: :collection
  end

  get 'home/index'

  devise_for :users
  root to: "home#index"

end

app/models/client.rb
class Client < ActiveRecord::Base
  has_many :works
  def full_name
    "#{self.first_name} #{self.last_name}"
  end
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  before_action :set_client, only: [:show, :edit, :update, :destroy]

  # GET /clients
  # GET /clients.json
  def index
    @clients = Client.all
  end

  # GET /clients/1
  # GET /clients/1.json
  def show
  end

  # GET /clients/new
  def new
    @client = Client.new
  end

  # GET /clients/1/edit
  def edit
  end

  # POST /clients
  # POST /clients.json
  def create
    @client = Client.new(client_params)

    respond_to do |format|
      if @client.save
        format.html { redirect_to @client, notice: 'Client was successfully created.' }
        format.json { render :show, status: :created, location: @client }
      else
        format.html { render :new }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /clients/1
  # PATCH/PUT /clients/1.json
  def update
    respond_to do |format|
      if @client.update(client_params)
        format.html { redirect_to @client, notice: 'Client was successfully updated.' }
        format.json { render :show, status: :ok, location: @client }
      else
        format.html { render :edit }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clients/1
  # DELETE /clients/1.json
  def destroy
    @client.destroy
    respond_to do |format|
      format.html { redirect_to clients_url, notice: 'Client was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_client
      @client = Client.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def client_params
      params.require(:client).permit(:first_name, :last_name, :phone_no, :mobile_no, :email, :on_vacation)
    end
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/views/clients/_form.html.erb
<%= simple_form_for @client do |f| %>
  <%= f.input :first_name %>
  <%= error_span(@client[:first_name]) %>
  <%= f.input :last_name %>
  <%= error_span(@client[:last_name]) %>
  <%= f.input :phone_no %>
  <%= error_span(@client[:phone_no]) %>
  <%= f.input :mobile_no %>
  <%= error_span(@client[:mobile_no]) %>
  <%= f.input :email %>
  <%= error_span(@client[:email]) %>
  <%= f.input :on_vacation %>
  <%= error_span(@client[:on_vacation]) %>

  <%= f.button :submit, :class => 'btn-primary' %>
  <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                clients_path, :class => 'btn btn-default' %>
<% end %>

app/views/clients/edit.html.erb
<%- model_class = Client -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<div class="container">
  <div class="row">
<div class="col-sm-12">
<%= render :partial => 'form' %>
</div>
  </div>
</div>

app/views/clients/index.html.erb
<%- model_class = Client -%>
<div class="container">
  <div class="row">
    <div class="col-sm-12">
      <h2>Clients</h2>
      <hr>
      <div class="table-responsive">
<table class="table table-striped table-bordered">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:first_name) %></th>
      <th><%= model_class.human_attribute_name(:last_name) %></th>
      <th><%= model_class.human_attribute_name(:phone_no) %></th>
      <th><%= model_class.human_attribute_name(:mobile_no) %></th>
      <th><%= model_class.human_attribute_name(:email) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @clients.each do |client| %>
      <tr <%= client.on_vacation == true ? "class=danger" : "" %>>
        <td><%= link_to client.id, client_path(client) %></td>
        <td><%= client.first_name %></td>
        <td><%= client.last_name %></td>
        <td><%= client.phone_no %></td>
        <td><%= client.mobile_no %></td>
        <td><%= client.email %></td>
        <td>
          <%= link_to "Modify",
                      edit_client_path(client), :class => 'btn btn-default btn-xs' %>
          </td>
      </tr>
    <% end %>
  </tbody>
</table>
      </div>
      <hr>

<%= link_to "New Client",
            new_client_path,
            :class => 'btn btn-primary' %>

    </div>
  </div>
</div>

app/views/clients/new.html.erb
<%- model_class = Client -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<div class="container">
  <div class="row">
  <div class="col-sm-12">
<%= render :partial => 'form' %>
</div>
  </div>
</div>

app/views/clients/show.html.erb
<%- model_class = Client -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:first_name) %>:</strong></dt>
  <dd><%= @client.first_name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:last_name) %>:</strong></dt>
  <dd><%= @client.last_name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:phone_no) %>:</strong></dt>
  <dd><%= @client.phone_no %></dd>
  <dt><strong><%= model_class.human_attribute_name(:mobile_no) %>:</strong></dt>
  <dd><%= @client.mobile_no %></dd>
  <dt><strong><%= model_class.human_attribute_name(:email) %>:</strong></dt>
  <dd><%= @client.email %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              clients_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_client_path(@client), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              client_path(@client),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>