config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  get 'reports/index'
  get 'reports/long'
  get 'reports/client'

  resources :attendances do
    get 'change', on: :collection
    post 'bulk', on: :collection
  end

  resources :works

  resources :payments

  resources :clients

  resources :labours do
    get 'salary', on: :collection
    get 'attendance', on: :collection
    post 'bs', on: :collection
    post 'as', on: :collection
  end

  get 'home/index'

  devise_for :users
  root to: "home#index"

end

app/models/payment.rb
class Payment < ActiveRecord::Base

end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController
  before_action :set_payment, only: :destroy
  def index
    @labours = Labour.where("labours.on_vacation is not true").order(:first_name)
  end

  def new
  end

  def show
    @labours = Labour.where("labours.on_vacation is not true").order(:first_name)
    @labour = Labour.find(params[:id])
  end

  def create
    params[:payment].each do |payment|
      logger.debug(payment[1])
      @payment = Payment.new(payment[1])
      unless @payment.amount_paid.blank?
      @payment.date = Date.strptime(payment[1]["date"],"%d-%m-%Y")
      @payment.save
    end
    end
    respond_to do |format|
      format.html { redirect_to :back , notice: 'payment was successfully created.' }
      format.json { render :show, status: :created, location: @payment }
    end
  end

  def update
  end

  def destroy
    @payment.destroy
    redirect_to payments_url , notice: "Payment has been deleted"
  end

    private
    # Use callbacks to share common setup or constraints between actions.
    def set_payment
      @payment = Payment.find(params[:id])
    end

end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/views/payments/create.html.erb
<h1>Payments#create</h1>
<p>Find me in app/views/payments/create.html.erb</p>

app/views/payments/index.html.erb
<div class="container">
  <div class="row">
    <div>Date: <input type="text" id="datepicker"> </div>
    <div class="col-sm-6">
            <%= simple_form_for 'payment', url: payments_path do |f| %>
    <div class="table-responsive">
        <table class="table table-bordered table-striped">
          <thead>
            <td>Labour</td>
            <td>Amount</td>
            <td>Comment</td>
          </thead>
          <tbody>

            <% @labours.each_with_index do |labour,i| %>
            <tr>

              <%= hidden_field_tag "payment[#{i}][date]" , Date.today, class: "date" %>
              <%= hidden_field_tag "payment[#{i}][labour_id]", labour.id %>
              <td><%= link_to "#{labour.first_name} #{labour.last_name}", payment_url(labour.id) %></td>
              <td><%= text_field_tag "payment[#{i}][amount_paid]" %></td>
              <td><%= text_field_tag "payment[#{i}][comment]" %></td>
            </tr>
            <% end %>
          </tbody>
        </table>
      </div>
      <%= f.button :submit, value: "Okay", class: "btn btn-primary btn-large" %>
      <% end %>

    </div>
    <div class="col-sm-6">
      <h2><%= @labours.first.first_name %> <%= @labours.first.last_name %></h2>
      Advanced Details: <%= !@labours.first.account_setteled_on.blank? ? (@labours.first.account_setteled_on + 1.day).strftime("%d-%m-%y") : @labours.first.date_of_joining.to_date.strftime("%d-%m-%y") %> to <%= Date.today.strftime("%d-%m-%y") %>.
      <%if @labours.first.account > 0 %>
      Advance : <%= number_with_precision(@labours.first.account, precision: 2) %>

      <%elsif @labours.first.account < 0 %>
      Advance : <%= number_with_precision(@labours.first.account, precision: 2) %>
      <% else %>
      No Balance.
      <% end %>
      <div style="border: 1px solid grey;"> Account Details
        <table class="table table-borderd table-striped">
          <thead>
            <td>Sr no</td>
            <td>Date</td>
            <td>Amount</td>
            <td>Comment</td>
            <td>Options</td>
          </thead>
          <tbody>
            <% if @labours.first.account_setteled_on.blank? %>
            <% start_date = @labours.first.date_of_joining %>
            <% else %>
            <% start_date = @labours.first.account_setteled_on + 1.day %>
            <% end %>
            <%= start_date %>
            <% Payment.where("labour_id = ? and date between ? and ?", @labours.first.id,start_date, Date.today).each_with_index do |p,i| %>
            <tr>
              <td><%= i %></td>
              <td><%= p.date.strftime("%d-%m-%y") %></td>
              <td><%= number_with_precision(p.amount_paid, precision: 2) %></td>
              <td><%= p.comment %></td>
              <td>  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      payment_path(p),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %></td>
            </tr>
            <% end %>
          </tbody>
        </table>
      </div>
      <table class="table table-bordered table-striped">
        <tbody>
          <tr>
            <td>Attendance Total</td>
            <td>
              <% hours = 0 %>
              <% salary = 0 %>
              <% advance = 0 %>
              <% Attendance.where("labour_id = ? and date >= ? and date <= ?", @labours.first.id,start_date, Date.today).each do |a|
                hours += a.hours unless a.hours.nil?
                salary += a.salary unless a.salary.nil?
              end
              %>
              <%= number_with_precision(hours/@labours.first.salary_for_hours, precision: 2)  %>
            </td>
          </tr>
          <tr>
            <td>Total Advance</td>
            <td>
              <% Payment.where("labour_id = ? and date >= ? and date <= ?", @labours.first.id,start_date, Date.today).each do |p|
                advance += p.amount_paid unless p.amount_paid.nil?
                end %>
                <%= number_with_precision(advance, precision: 2) %>

              </td>
            </tr>
            <tr>
              <td>Total Salary</td>
              <td>
                <%= number_with_precision(salary, precision: 2) %>
              </td>
            </tr>
            <tr>
              <td>Net Payable</td>
              <td>
                <%= number_with_precision(net = salary - advance, precision: 2) %>
              </td>
            </tr>
          </tbody>
        </table>
        <%= simple_form_for :labour , method: "patch", url: labour_path(@labours.first) do |f|  -%>
        <%= f.input :account_setteled_on , input_html: { id: "datepicker2"} %>
        <%= f.hidden_field :account, value:(@labours.first.account + net )%>
        <%= f.button :submit, class: "btn btn-primary", value: "Settle account" %>
        <% end -%>
      </div>
    </div>
  </div>

  <script>
    $("#datepicker").on("change", function(){
      $(".date").each(function(){
        $(this).val($("#datepicker").val());
      });
    });
  </script>

app/views/payments/show.html.erb
<div class="container">
  <div class="row">
    <div>Date: <input type="text" id="datepicker"> </div>

            <% end_date = params.has_key?(:upto_date) ? Date.strptime(params[:upto_date],"%d-%m-%Y") : Date.today  %>
    <div class="col-sm-6">
      <%= simple_form_for 'payment', url: payments_path do |f| %>
      <div class="table-responsive">
        <table class="table table-bordered table-striped">
          <thead>
            <td>Labour</td>
            <td>Amount</td>
            <td>Comment</td>
          </thead>
          <tbody>
            <% @labours.each_with_index do |labour,i| %>
            <tr>
              <%= hidden_field_tag "payment[#{i}][date]" , Date.today, class: "date" %>
              <%= hidden_field_tag "payment[#{i}][labour_id]", labour.id %>
              <td><%= link_to "#{labour.first_name} #{labour.last_name}", payment_url(labour.id) %></td>
              <td><%= text_field_tag "payment[#{i}][amount_paid]" %></td>
              <td><%= text_field_tag "payment[#{i}][comment]" %></td>
            </tr>
            <% end %>
          </tbody>
        </table>
      </div>
      <%= f.button :submit, value: "Okay", class: "btn btn-primary btn-large" %>
      <% end %>

    </div>
    <div class="col-sm-6">
      <h2><%= @labour.first_name %> <%= @labour.last_name %></h2>


      Advanced Details: <%= !@labour.account_setteled_on.blank? ? (@labour.account_setteled_on + 1.day).strftime("%d-%m-%y") : @labour.date_of_joining.to_date.strftime("%d-%m-%y") %> to <form action="/payments/<%= params[:id] %>" method="get"><input type="text" name="upto_date" id="datepicker3" value="<%= end_date.strftime("%d-%m-%y") %>"> <button class="btn btn-primary">go</button></form>

      <%if @labour.account > 0 %>
      Balance : <%= number_with_precision(@labour.account, precision: 2) %>

      <%elsif @labour.account < 0 %>
      Advance : <%= number_with_precision(@labour.account, precision: 2) %>
      <% else %>
      No Balance.
      <% end %>
      <hr>
      <div style="border: 1px solid grey; margin: -1px 0px 0px -1px;"> <p class="text-center"> Account Details </p>
        <table class="table table-borderd table-striped">
          <thead>
            <td>Sr no</td>
            <td>Date</td>
            <td>Amount</td>
            <td>Comment</td>
          </thead>
          <tbody>
            <% if @labour.account_setteled_on.blank? %>
            <% start_date = @labour.date_of_joining %>
            <% else %>
            <% start_date = @labour.account_setteled_on + 1.day %>
            <% end %>
            <% Payment.where("labour_id = ? and date between ? and ?", @labour.id,start_date, end_date ).each_with_index do |p,i| %>
            <tr>
              <td><%= i %></td>
              <td><%= p.date.strftime("%d-%m-%y") %></td>
              <td><%= number_with_precision(p.amount_paid, precision: 2) %></td>
              <td><%= p.comment %></td>
              <td>  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                payment_path(p),
                :method => :delete,
                :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                :class => 'btn btn-xs btn-danger' %></td>
              </tr>
              <% end %>
            </tbody>
          </table>
        </div>
        <table class="table table-bordered table-striped">
          <tbody>
            <tr>
              <td>Attendance Total</td>
              <td>
                <% hours = 0 %>
                <% salary = 0 %>
                <% advance = 0 %>
                <% Attendance.where("labour_id = ? and date >= ? and date <= ?", @labour.id,start_date, end_date).each do |a|
                  hours += a.hours unless a.hours.nil?
                  salary += a.salary unless a.salary.nil?
                end
                %>
                <%= number_with_precision(hours/@labour.salary_for_hours, precision: 2)  %>
              </td>
            </tr>
            <tr>
              <td>Total Advance</td>
              <td>
                <% Payment.where("labour_id = ? and date >= ? and date <= ?", @labour.id,start_date, end_date).each do |p|
                  advance += p.amount_paid unless p.amount_paid.nil?
                  end %>
                  <%= number_with_precision(advance, precision: 2) %>

                </td>
              </tr>
              <tr>
                <td>Total Salary</td>
                <td>
                  <%= number_with_precision(salary, precision: 2) %>
                </td>
              </tr>
              <tr>
                <td>Net Payable</td>
                <td>
                  <%= number_with_precision(net = salary - advance, precision: 2) %>
                </td>
              </tr>
            </tbody>
          </table>

            <%= simple_form_for :labour , method: "patch", url: labour_path(@labour), remote: true do |f|  -%>
          <%= f.hidden_field :account_setteled_on , id: "settle" , value: (params.fetch(:upto_date , "#{Date.today}")) %>
          <%= f.hidden_field :account, value:(@labour.account + net )%>
          <%= f.button :submit, class: "btn btn-primary", value: "Settle account" %>
          <% end -%>
        </div>
      </div>
    </div>
    <script>
      $("#datepicker").on("change", function(){
        $(".date").each(function(){
          $(this).val($("#datepicker").val());
        });
      });
      $("#datepicker3").on("change", function(){
          $("#settle").val($("#datepicker3").val());
      });
    </script>

app/views/payments/update.html.erb
<h1>Payments#update</h1>
<p>Find me in app/views/payments/update.html.erb</p>