config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  get 'reports/index'
  get 'reports/long'
  get 'reports/client'

  resources :attendances do
    get 'change', on: :collection
    post 'bulk', on: :collection
  end

  resources :works

  resources :payments

  resources :clients

  resources :labours do
    get 'salary', on: :collection
    get 'attendance', on: :collection
    post 'bs', on: :collection
    post 'as', on: :collection
  end

  get 'home/index'

  devise_for :users
  root to: "home#index"

end

app/views/layouts/_header.html.erb
<header>
  <nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-menu">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to root_path, class: "navbar-brand logo-header" do %>
<% end %>
      <div class="collapse navbar-collapse" id="navbar-menu">
      <ul class="nav navbar-nav navbar-right">

      <li><a data-toggle="modal" style="cursor: pointer;" data-target="#property_alert">Property Alerts</a></li>
      <li><a href="/localities">Localities</a></li>
      <li><a href="/projects">New Projects</a></li>
      <% unless user_signed_in? %>
        <li><a href="/users/sign_in">Login</a></li>
        <li><a href="/users/sign_up">Signup</a></li>
        <% else %>
        <li><p class="navbar-text" style="font-weight:600;">Welcome,  <%= current_user.first_name.titlecase %></p></li>
        <li><%= link_to('Logout', destroy_user_session_path, :method => :delete)  %></li>
        <% end %>
     <li><a class="btn btn-primary btn-block btn-primary-pf" style="color: white !important; margin-top:8px; padding:8px;" href="/rents/new">List Your Property</a></li>
      </ul>

    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Lama</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>

  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
</head>
<body>
  <nav class="navbar navbar-default" role="navigation">
    <div class="container-fluid">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="/">Labour Management</a>
      </div>

      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-left">
        <li>
        <% if cookies[:s] == 'c' %>
          <p class="navbar-text text-success">Company</p>
          <% else %>
          <p class="navbar-text text-success">Personal</p>
          <% end %>
        </li>
      </ul>
        <ul class="nav navbar-nav navbar-right">

          <li><a href="#"><strong>Material</strong></a></li>

          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown"><strong>Labours</strong><b class="caret"></b></a>
            <ul class="dropdown-menu">
              <li><%= link_to "Add New Labour", new_labour_path %></li>
              <li><%= link_to "View All Labours", labours_path %></li>
              <li><%= link_to "Change Salary", salary_labours_path %></li>
              <li><%= link_to "Change Attendance", attendance_labours_path %></li>
            </ul>
          </li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown"><strong>Clients</strong><b class="caret"></b></a>
            <ul class="dropdown-menu">
              <li><%= link_to "Add New Client", new_client_path %></li>
              <li><%= link_to "View All Clients", clients_path %></li>
            </ul>
          </li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown"><strong>Works</strong><b class="caret"></b></a>
            <ul class="dropdown-menu">
              <li><%= link_to "Add New Work", new_work_path %></li>
              <li><%= link_to "View All Works", works_path %></li>
            </ul>
          </li>
              <li><%= link_to "Attendance", attendances_path %></li>
              <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown"><strong>Payments</strong><b class="caret"></b></a>
            <ul class="dropdown-menu">
              <li><%= link_to "Payments Labour", payments_path %></li>
            </ul>
          </li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown"><strong>Reports</strong><b class="caret"></b></a>
            <ul class="dropdown-menu">
              <li><%= link_to "Short Report", reports_index_path(startdate: (Date.today - 1.month), enddate: Date.today) %></li>
              <li><%= link_to "Long Report", reports_long_path %></li>
              <li><%= link_to "Client Report", reports_client_path %></li>
            </ul>
          </li>

        </ul>
      </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
  </nav>
  <%= notice %>
   <% if current_user %>
   <%= link_to "Logout", destroy_user_session_path, method: :delete %>
  <% else %>
  <%= link_to "Login", new_user_session_path %>
   <% end %> 

  <%= yield %>
  <script>
  $(function() {
    $( "#datepicker" ).datepicker( {dateFormat: "dd-mm-yy"} );
  });
  $(function() {
    $( "#datepicker2" ).datepicker({dateFormat:  "dd-mm-yy"});
  });
  $(function() {
    $( "#datepicker3" ).datepicker({dateFormat:  "dd-mm-yy"});
  });
  </script>
</body>
</html>